name: "Build BuilderDAO CLI"
description: "Build BuilderDAO CLI"

runs:
  using: "composite"
  steps:
    # - uses: ./.github/actions/install-node-dependencies
    - run: yarn global add @builderdao/cli 
      shell: bash