# Implicit dependencies
# - actions/checkout@v2
# - ./.github/actions/install-linux-build-deps
# - ./.github/actions/install-solana
# - ./.github/actions/install-rust

name: Build Tutorial Program 
runs:
  using: 'composite'
  steps:
    - uses: ./.actions/
    - name: build-tutorial-program
      working-directory: ./dao-programs/programs/tutorial
      run: |
        anchor build
        anchor test
      shell: bash